sudo: required

language: generic

services:
  - docker

before_install:
  - docker build -t ravindar86/docker-react -f DockerFile.dev .

script:
  - docker run -e CI=true ravindar86/docker-react npm run test
